name: dart_stack
description: Stack data structure implemention for dart language.
version: 0.1.0
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
dev_dependencies:
  flutter_lints: ^1.0.0